# Generated by Django 3.2.5 on 2021-07-15 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='prcie',
            new_name='price',
        ),
    ]
